apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app.kubernetes.io/component: frontend-services
    app.kubernetes.io/part-of: easytrade
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        app.kubernetes.io/component: frontend-services
        app.kubernetes.io/part-of: easytrade
    spec:
      containers:
        - name: frontend
          image: frontend
          ports:
            - containerPort: 3000
          env: []
          resources:
            requests:
              cpu: 10m
              memory: 75Mi
            limits:
              memory: 75Mi
      imagePullSecrets:
        - name: frontend-services
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
