apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
      app.kubernetes.io/version: v1
  template:
    metadata:
      labels:
        app: db
        app.kubernetes.io/part-of: easytrade
        app.kubernetes.io/version: v1
    spec:
      containers:
        - name: db
          image: db
          ports:
            - containerPort: 1433
          env:
            - name: SA_PASSWORD
              value: "yourStrong(!)Password"
          resources:
            requests:
              cpu: 40m
              memory: 1.5Gi
            limits:
              memory: 1.5Gi
      imagePullSecrets:
        - name: proddeploycred 
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP
  selector:
    app: db
    app.kubernetes.io/version: v1
  ports:
    - name: mssql
      port: 1433
      targetPort: 1433
