apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine
spec:
  selector:
    matchLabels:
      app: engine
      app.kubernetes.io/version: v1
  template:
    metadata:
      labels:
        app: engine
        app.kubernetes.io/part-of: easytrade
        app.kubernetes.io/version: v1
    spec:
      containers:
        - name: engine
          image: engine
          ports:
            - containerPort: 8080
          env:
            - name: BROKER_HOSTANDPORT
              value: "broker-service:8080"
            - name: PROXY_PREFIX
              value: "engine"
          resources:
            requests:
              cpu: 10m
              memory: 450Mi
            limits:
              memory: 450Mi
      imagePullSecrets:
        - name: proddeploycred 
---
apiVersion: v1
kind: Service
metadata:
  name: engine
spec:
  type: ClusterIP
  selector:
    app: engine
    app.kubernetes.io/version: v1
  ports:
    - name: http
      port: 8080
      targetPort: 8080
