apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-flag-service
  labels:
        app.kubernetes.io/part-of: easytrade
        app.kubernetes.io/component: background-services
spec:
  selector:
    matchLabels:
      app: feature-flag-service
      app.kubernetes.io/version: v1
  template:
    metadata:
      labels:
        app: feature-flag-service
        app.kubernetes.io/part-of: easytrade
        app.kubernetes.io/version: v1
        app.kubernetes.io/component: background-services
    spec:
      containers:
        - name: feature-flag-service
          image: feature-flag-service
          ports:
            - containerPort: 8080
          env: []
          resources:
            requests:
              cpu: 30m
              memory: 600Mi
            limits:
              memory: 600Mi
      imagePullSecrets:
        - name: proddeploycred 
---
apiVersion: v1
kind: Service
metadata:
  name: feature-flag-service
spec:
  type: ClusterIP
  selector:
    app: feature-flag-service
    app.kubernetes.io/version: v1
  ports:
    - name: feature-flag-service
      port: 8080
      targetPort: 8080
