apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountservice
  labels:
        app.kubernetes.io/part-of: easytrade
        app.kubernetes.io/component: background-services
spec:
  selector:
    matchLabels:
      app: accountservice
      app.kubernetes.io/version: v1
  template:
    metadata:
      labels:
        app: accountservice
        app.kubernetes.io/part-of: easytrade
        app.kubernetes.io/version: v1
        app.kubernetes.io/component: background-services
    spec:
      containers:
        - name: accountservice
          image: accountservice
          ports:
            - containerPort: 8080
          env:
            - name: MANAGER_HOSTANDPORT
              value: "manager:8080"
            - name: PROXY_PREFIX
              value: "accountservice"
          resources:
            requests:
              cpu: 30m
              memory: 600Mi
            limits:
              memory: 600Mi
      imagePullSecrets:
        - name: proddeploycred
---
apiVersion: v1
kind: Service
metadata:
  name: accountservice
spec:
  type: ClusterIP
  selector:
    app: accountservice
    app.kubernetes.io/version: v1
  ports:
    - name: http
      port: 8080
      targetPort: 8080