apiVersion: v1
kind: ConfigMap
metadata:
  name: aggregator-service-envs
data:
  OFFER_SERVICE_PROTOCOL: "http"
  OFFER_SERVICE_HOST: "offerservice"
  OFFER_SERVICE_PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-service
spec:
  selector:
    matchLabels:
      app: aggregator-service
      app.kubernetes.io/version: v1
  template:
    metadata:
      labels:
        app: aggregator-service
        app.kubernetes.io/part-of: easytrade
        app.kubernetes.io/version: v1
    spec:
      containers:
        - name: aggregator-service
          image: aggregator-service
          env: []
          envFrom:
            - configMapRef:
                name: aggregator-service-envs
          resources:
            requests:
              cpu: 10m
              memory: 30Mi
            limits:
              memory: 30Mi
      imagePullSecrets:
        - name: proddeploycred 
