apiVersion: apps/v1
kind: Deployment
metadata:
  name: contentcreator
  labels:
        app.kubernetes.io/part-of: easytrade
        app.kubernetes.io/component: backend
spec:
  selector:
    matchLabels:
      app: contentcreator
      app.kubernetes.io/version: v1
  template:
    metadata:
      labels:
        app: contentcreator
        app.kubernetes.io/version: v1
        app.kubernetes.io/part-of: easytrade
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: contentcreator
          image: contentcreator
          env:
            - name: MSSQL_CONNECTIONSTRING
              valueFrom:
                configMapKeyRef:
                  name: connection-strings
                  key: JAVA_CONNECTION_STRING
          resources:
            requests:
              cpu: 10m
              memory: 400Mi
            limits:
              memory: 400Mi
      imagePullSecrets:
        - name: proddeploycred 