apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendreverseproxy
spec:
  selector:
    matchLabels:
      app: frontendreverseproxy
      app.kubernetes.io/version: v1
  template:
    metadata:
      labels:
        app: frontendreverseproxy
        app.kubernetes.io/part-of: easytrade
        app.kubernetes.io/version: v1
    spec:
      containers:
        - name: frontendreverseproxy
          image: frontendreverseproxy
          ports:
            - containerPort: 80
          env: []
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              memory: 100Mi
      imagePullSecrets:
        - name: proddeploycred 
---
apiVersion: v1
kind: Service
metadata:
  name: frontendreverseproxy-easytrade
spec:
  type: LoadBalancer
  selector:
    app: frontendreverseproxy
    app.kubernetes.io/version: v1
  ports:
    - name: http
      port: 80
      targetPort: 80
