apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
        app.kubernetes.io/part-of: easytrade
        app.kubernetes.io/component: frontend-services
spec:
  selector:
    matchLabels:
      app: frontend
      app.kubernetes.io/version: v1
  template:
    metadata:
      labels:
        app: frontend
        app.kubernetes.io/part-of: easytrade
        app.kubernetes.io/version: v1
        app.kubernetes.io/component: frontend-services
    spec:
      containers:
        - name: frontend
          image: frontend
          ports:
            - containerPort: 3000
          env: []
          resources:
            requests:
              cpu: 10m
              memory: 75Mi
            limits:
              memory: 75Mi
      imagePullSecrets:
        - name: proddeploycred 
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
    app.kubernetes.io/version: v1
  ports:
    - name: http
      port: 3000
      targetPort: 3000
