apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
spec:
  selector:
    matchLabels:
      app: manager
      app.kubernetes.io/version: v1
  template:
    metadata:
      labels:
        app: manager
        app.kubernetes.io/version: v1
    spec:
      containers:
        - name: manager
          image: manager
          ports:
            - containerPort: 8080
          env:
            - name: PROXY_PREFIX
              value: "manager"
            - name: MSSQL_CONNECTIONSTRING
              valueFrom:
                configMapKeyRef:
                  name: connection-strings
                  key: DOTNET_CONNECTION_STRING
          resources:
            requests:
              cpu: 50m
              memory: 300Mi
            limits:
              memory: 300Mi
      imagePullSecrets:
        - name: proddeploycred 
---
apiVersion: v1
kind: Service
metadata:
  name: manager
spec:
  type: ClusterIP
  selector:
    app: manager
    app.kubernetes.io/version: v1
  ports:
    - name: http
      port: 8080
      targetPort: 8080
