apiVersion: v1
kind: ConfigMap
metadata:
  name: offerservice-envs
data:
  LOGIN_SERVICE_PORT: "8080"
  LOGIN_SERVICE_BASE_URL: loginservice
  MANAGER_BASE_URL: manager
  MANAGER_PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: offerservice
spec:
  selector:
    matchLabels:
      app: offerservice
      app.kubernetes.io/version: v1
  template:
    metadata:
      labels:
        app: offerservice
        app.kubernetes.io/version: v1
    spec:
      containers:
        - name: offerservice
          image: offerservice
          ports:
            - containerPort: 8080
          env: []
          envFrom:
            - configMapRef:
                name: offerservice-envs
            - configMapRef:
                name: feature-flag-service-setup
          resources:
            requests:
              cpu: 50m
              memory: 150Mi
            limits:
              memory: 150Mi
      imagePullSecrets:
        - name: proddeploycred 
---
apiVersion: v1
kind: Service
metadata:
  name: offerservice
spec:
  type: ClusterIP
  selector:
    app: offerservice
    app.kubernetes.io/version: v1
  ports:
    - name: http
      port: 8080
      targetPort: 8080
