apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculationservice
  labels:
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: easytrade
spec:
  selector:
    matchLabels:
      app: calculationservice
  template:
    metadata:
      labels:
        app: calculationservice
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: easytrade
    spec:
      containers:
        - name: calculationservice
          image: calculationservice
          env: []
          envFrom:
            - configMapRef:
                name: rabbitmq-vars
          resources:
            requests:
              cpu: 10m
              memory: 25Mi
            limits:
              memory: 25Mi
      imagePullSecrets:
        - name: background-services
