apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loadgen
  name: loadgen
spec:
  selector:
    matchLabels:
      app: loadgen
  template:
    metadata:
      labels:
        app: loadgen
    spec:
      containers:
        - name: loadgen
          image: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade/loadgen:latest
          env:
            - name: EASYTRADE_URL
              value: "http://frontendreverseproxy-easytrade.prod.svc.cluster.local"
            - name: CONCURRENCY
              value: "2"
            - name: BROWSER_TTL_MINUTES
              value: "10"
          resources:
            requests:
              cpu: "1"
              memory: 1Gi
            limits:
              memory: 1Gi