
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountservice
  labels:
        app.kubernetes.io/component: background-services
        app.kubernetes.io/part-of: easytrade
spec:
  selector:
    matchLabels:
      app: accountservice
  template:
    metadata:
      labels:
        app: accountservice
        app.kubernetes.io/component: background-services
        app.kubernetes.io/part-of: easytrade
    spec:
      containers:
        - name: accountservice
          image: accountservice
          ports:
            - containerPort: 8080
          env:
            - name: MANAGER_HOSTANDPORT
              value: "manager:8080"
            - name: PROXY_PREFIX
              value: "accountservice"
          resources:
            requests:
              cpu: 30m
              memory: 300Mi
            limits:
              memory: 300Mi
      imagePullSecrets:
        - name: background-services
---
apiVersion: v1
kind: Service
metadata:
  name: accountservice
spec:
  type: ClusterIP
  selector:
    app: accountservice
  ports:
    - name: http
      port: 8080
      targetPort: 8080